<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="ProfileAssignmentsBusiness">
  <testsuite name="Login to CB as primaryadmin" id="f876fe13-154f-4e37-b680-0f658bf29f93" tests="1" time="1077">
    <testcase name="status code is 201 : Created"/>
  </testsuite>
  <testsuite name="Add Business Profile" id="fa776692-f203-4d4a-963d-f497d195365b" tests="0" time="0">
    <error>
      <![CDATA[Iteration: 0
RequestError: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)

---
testScriptError: ReferenceError: responseBody is not defined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:3:27)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
  </testsuite>
  <testsuite name="get profile by Id copy" id="f618f7ba-4ab4-48f9-87e1-d5aa1b9f6a85" tests="1" time="957">
    <error>
      <![CDATA[Iteration: 0

---
testScriptError: TypeError: Cannot read property 'ChannelProfiles' of undefined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:5:21)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
    <testcase name="status code is 200 : OK">
      <failure type="AssertionFailure">
        <![CDATA[Failed 1 times.]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="business user add with profile" id="75302638-4ac2-4cb7-9b98-67efab3bbe97" tests="1" time="909">
    <error>
      <![CDATA[Iteration: 0

---
testScriptError: TypeError: Cannot read property 'Id' of undefined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:5:51)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
    <testcase name="status code is 201 : Created">
      <failure type="AssertionFailure">
        <![CDATA[Failed 1 times.]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="Get Business Users with profile" id="61aaa248-5f42-4bcc-b5b2-f86375c4124b" tests="0" time="890">
    <error>
      <![CDATA[Iteration: 0

---
testScriptError: TypeError: Cannot read property 'UserName' of undefined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:4:53)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
  </testsuite>
  <testsuite name="modify business user" id="b898b1c5-338e-4a62-93fc-dac213dbb273" tests="1" time="893">
    <testcase name="status code is 204 : No Content">
      <failure type="AssertionFailure">
        <![CDATA[Failed 1 times.]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="Get Business Users with profile copy" id="1896a54a-335d-4963-a777-695e7a1762ca" tests="0" time="909">
    <error>
      <![CDATA[Iteration: 0

---
testScriptError: TypeError: Cannot read property 'UserName' of undefined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:4:53)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
  </testsuite>
  <testsuite name="business user add without profile" id="6dd6aa65-4cca-4c75-94c6-bddfc3dd3ffa" tests="1" time="892">
    <testcase name="Profile is required."/>
  </testsuite>
  <testsuite name="business user add with channel profile" id="4a78a150-c668-463d-8f4b-06176ee56ea9" tests="1" time="891">
    <testcase name="Profile ID is Invalid.">
      <failure type="AssertionFailure">
        <![CDATA[Failed 1 times.]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="business user add with retailUser profile" id="454adc39-ded5-4654-9550-727041266bc8" tests="1" time="879">
    <testcase name="Profile ID is Invalid."/>
  </testsuite>
  <testsuite name="business user add with invalid profileId" id="af7f641c-602d-42a8-aee6-bd5413fe6693" tests="1" time="1085">
    <testcase name="Profile ID is Invalid."/>
  </testsuite>
  <testsuite name="business user add with multiple profile" id="9f1588d4-8ba1-4ed6-b9fd-0cff87095c6f" tests="1" time="970">
    <testcase name="User can be assigned to only one Profile."/>
  </testsuite>
  <testsuite name="Login to CB as jolina" id="2ff2595f-ba1c-4cdf-857e-0d20dfe554b2" tests="1" time="858">
    <testcase name="status code is 201 : Created"/>
  </testsuite>
  <testsuite name="Add Business Profile with user not entitled to add" id="1fa68880-02ca-4e61-b5d9-40a71e31cd3d" tests="1" time="440">
    <testcase name="status code is 400 : Bad Request"/>
  </testsuite>
  <testsuite name="business user add with profile with user not entitled" id="c000feb7-dcc3-44e2-ab17-d8fdb27ee0f4" tests="1" time="764">
    <testcase name="status code is 400 : Bad Request"/>
  </testsuite>
  <testsuite name="Login to CB as secondaryadmin" id="2fef74c3-cd3c-4b94-bcdf-90316906c273" tests="1" time="820">
    <testcase name="status code is 201 : Created"/>
  </testsuite>
  <testsuite name="Add Business Profile with secondaryadmin" id="094aaf80-d6de-4eec-b190-8e30f07390e4" tests="1" time="340">
    <testcase name="status code is 201 : Created"/>
  </testsuite>
  <testsuite name="business user add with secondaryadmin" id="cb17f2a5-db78-42b5-ae47-f7eaab87879c" tests="0" time="0">
    <error>
      <![CDATA[Iteration: 0
RequestError: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)

---
testScriptError: ReferenceError: responseCode is not defined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:3:41)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
  </testsuite>
  <testsuite name="delete assigned profile" id="adf154bd-1cc8-4ccb-b3c0-9fcd4c502475" tests="1" time="1748">
    <testcase name="Can not delete assigned Profile."/>
  </testsuite>
</testsuites>