<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="ProfileAssignmentsBusiness">
  <testsuite name="Login to CB as primaryadmin" id="6b5ad074-9def-4074-a05f-e6abb17e42ae" tests="1" time="1549">
    <testcase name="status code is 201 : Created"/>
  </testsuite>
  <testsuite name="Add Business Profile" id="dabe00c5-41a3-467d-87d6-712029958c23" tests="0" time="0">
    <error>
      <![CDATA[Iteration: 0
RequestError: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)

---
testScriptError: ReferenceError: responseBody is not defined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:3:27)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
  </testsuite>
  <testsuite name="get profile by Id copy" id="14bcc068-d3c7-41da-994a-8951ea00d065" tests="1" time="1542">
    <error>
      <![CDATA[Iteration: 0

---
testScriptError: TypeError: Cannot read property 'ChannelProfiles' of undefined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:5:21)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
    <testcase name="status code is 200 : OK">
      <failure type="AssertionFailure">
        <![CDATA[Failed 1 times.]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="business user add with profile" id="e50bdc8b-6353-4a6b-a0b4-871375dd82fd" tests="1" time="904">
    <error>
      <![CDATA[Iteration: 0

---
testScriptError: TypeError: Cannot read property 'Id' of undefined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:5:51)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
    <testcase name="status code is 201 : Created">
      <failure type="AssertionFailure">
        <![CDATA[Failed 1 times.]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="Get Business Users with profile" id="47c3637f-3b55-4455-87bd-bfdba43151d7" tests="0" time="3868">
    <error>
      <![CDATA[Iteration: 0

---
testScriptError: TypeError: Cannot read property 'UserName' of undefined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:4:53)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
  </testsuite>
  <testsuite name="modify business user" id="2bba6840-8963-4f16-8a03-b0713a71c058" tests="1" time="892">
    <testcase name="status code is 204 : No Content">
      <failure type="AssertionFailure">
        <![CDATA[Failed 1 times.]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="Get Business Users with profile copy" id="4e54e64b-8378-47de-9fb0-71237a68f1e2" tests="0" time="875">
    <error>
      <![CDATA[Iteration: 0

---
testScriptError: TypeError: Cannot read property 'UserName' of undefined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:4:53)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
  </testsuite>
  <testsuite name="business user add without profile" id="86806e0e-c943-4a2f-bc6e-94a4438a41db" tests="1" time="881">
    <testcase name="Profile is required."/>
  </testsuite>
  <testsuite name="business user add with channel profile" id="b6fb763a-57ff-4fb9-963c-3014ef229a44" tests="1" time="3862">
    <testcase name="Profile ID is Invalid.">
      <failure type="AssertionFailure">
        <![CDATA[Failed 1 times.]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="business user add with retailUser profile" id="70cf62e3-c46d-47d0-bf18-b796598b8be4" tests="1" time="894">
    <testcase name="Profile ID is Invalid."/>
  </testsuite>
  <testsuite name="business user add with invalid profileId" id="b2499d91-523b-46e9-ad03-6ab8b498d3c9" tests="1" time="1037">
    <testcase name="Profile ID is Invalid."/>
  </testsuite>
  <testsuite name="business user add with multiple profile" id="7736a042-823f-47f5-9421-7293695b3d85" tests="1" time="877">
    <testcase name="User can be assigned to only one Profile."/>
  </testsuite>
  <testsuite name="Login to CB as jolina" id="ec96801e-c141-4c03-bdd7-5abf37864f16" tests="1" time="1575">
    <testcase name="status code is 201 : Created"/>
  </testsuite>
  <testsuite name="Add Business Profile with user not entitled to add" id="747146bf-bb6d-40cf-9864-561dfb9377fd" tests="1" time="442">
    <testcase name="status code is 400 : Bad Request"/>
  </testsuite>
  <testsuite name="business user add with profile with user not entitled" id="a8692629-257c-4e5b-be9a-ee0b1e04050b" tests="1" time="772">
    <testcase name="status code is 400 : Bad Request"/>
  </testsuite>
  <testsuite name="Login to CB as secondaryadmin" id="61a2525b-88b0-445c-852c-7504159e6ff2" tests="1" time="831">
    <testcase name="status code is 201 : Created"/>
  </testsuite>
  <testsuite name="Add Business Profile with secondaryadmin" id="ec172a3c-2cf2-4f3d-89b7-36e958464d26" tests="1" time="338">
    <testcase name="status code is 201 : Created"/>
  </testsuite>
  <testsuite name="business user add with secondaryadmin" id="1c28c274-055c-4a4a-98c6-d7e15a76082a" tests="0" time="0">
    <error>
      <![CDATA[Iteration: 0
RequestError: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)

---
testScriptError: ReferenceError: responseCode is not defined
    at Object.eval (eval at <anonymous> (evalmachine.<anonymous>:284:34), <anonymous>:3:41)
    at evalmachine.<anonymous>:293:23
    at evalmachine.<anonymous>:299:2
    at Object.exports.runInContext (vm.js:44:17)
    at _.extend._run (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:156:16)
    at _.extend.execute (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\uvm\host.js:121:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:179:27)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1144:13
    at replenish (C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1018:21)
    at C:\Users\I329272\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:1022:13
---
]]>
    </error>
  </testsuite>
  <testsuite name="delete assigned profile" id="5ec29258-3a57-4377-aa25-7ac31d6ec7c8" tests="1" time="2125">
    <testcase name="Can not delete assigned Profile."/>
  </testsuite>
</testsuites>